#!/bin/bash
# Package Shiki into shiki.zip.
# The archive root is shiki/.
# Non-Markdown files are renamed with a .md suffix and restored by unpack.md.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$SCRIPT_DIR/shiki.zip"
TMP_DIR="$SCRIPT_DIR/.tmp_pack"

# Clean and initialize.
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR/shiki"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

echo "Packaging Shiki framework..."

# 1. Root files.
ROOT_FILES=(
    README.md
    CHEATSHEET.md
    shiki.config.yaml
)

for f in "${ROOT_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$f" ]; then
        cp "$SCRIPT_DIR/$f" "$TMP_DIR/shiki/"
    else
        echo "WARN: missing file skipped: $f"
    fi
done

# 2. Core directories.
CORE_DIRS=(
    user-interface
    core-kernel
    tools-skills
    tech-stacks
    providers
)

# tests/fixtures/, shiki_context/, CLAUDE.md, and verification scripts are
# repository maintenance assets and are excluded from distribution packages.

for d in "${CORE_DIRS[@]}"; do
    if [ -d "$SCRIPT_DIR/$d" ]; then
        cp -r "$SCRIPT_DIR/$d" "$TMP_DIR/shiki/"
    else
        echo "WARN: missing directory skipped: $d"
    fi
done

# 3. Remove local generated files.
find "$TMP_DIR/shiki" -name ".DS_Store" -delete 2>/dev/null || true
find "$TMP_DIR/shiki" -type d -name "__pycache__" -prune -exec rm -rf {} + 2>/dev/null || true
find "$TMP_DIR/shiki" -name "*.pyc" -delete 2>/dev/null || true
rm -f "$TMP_DIR/shiki/tools-skills/scripts/verify.py"
rm -f "$TMP_DIR/shiki/tools-skills/scripts/simulate_scenarios.py"

# 4. Rename non-Markdown files and generate the mapping table.
MAPFILE="$TMP_DIR/shiki/_filemap.md"
echo "# File Mapping (auto-generated by pack.sh)" > "$MAPFILE"
echo "# Format: renamed_path -> original_path" >> "$MAPFILE"
echo "" >> "$MAPFILE"

HAS_RENAME=false

# Rename every non-Markdown file and record the original path.
find "$TMP_DIR/shiki" -type f ! -name "*.md" | while read -r filepath; do
    # Relative to shiki/.
    relpath="${filepath#$TMP_DIR/shiki/}"
    newpath="${filepath}.md"
    newrel="${relpath}.md"
    mv "$filepath" "$newpath"
    echo "$newrel -> $relpath" >> "$MAPFILE"
    HAS_RENAME=true
done

# 5. Copy the restore script.
cp "$SCRIPT_DIR/unpack.md" "$TMP_DIR/shiki/" 2>/dev/null || true

# 6. Create the archive.
rm -f "$OUTPUT"
cd "$TMP_DIR"
zip -rq shiki.zip shiki -x "*.DS_Store"
mv shiki.zip "$OUTPUT"

echo "Done: $OUTPUT"
echo "After extracting, run: cd shiki && python unpack.md"
